apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kanban_app.fullname }}
  labels:
    app.kubernetes.io/name: {{ .Values.kanban_app.fullname }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.kanban_app.serviceType }}
  selector:
    app: {{ .Values.kanban_app.fullname }}
  ports:
    - port: 8080
      targetPort: 8080