apiVersion: v1
kind: Service
metadata:
  name: {{ template "postgresql.master.fullname" . }}-svc
  labels:
    app.kubernetes.io/name: {{ template "postgresql.master.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.postgres.serviceType }}
  selector:
    app: {{ template "postgresql.master.fullname" . }}
  ports:
    - port: 5432
      targetPort: 5432