apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kanban_ui.fullname }}
  labels:
    app.kubernetes.io/name: {{ template "postgresql.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.kanban_ui.serviceType }}
  selector:
    app: {{ .Values.kanban_ui.fullname }}
  ports:
    - port: 80
      targetPort: 80