---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kanban
  name: deployment-ui
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-kan
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-kan
    spec:
      containers:
      - image: <frontend-image>
        imagePullPolicy: Always
        name: app-ui
        ports:
        - containerPort: 80
        
---
apiVersion: v1
kind: Service
metadata:
  namespace: kanban
  name: service-ui
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: app-kan
---
